version: '2'
services:
  spark-master:
    image: medu5a/spark-master-worker
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf/master
      SPARK_PUBLIC_DNS: localhost
      constraint:node=: swarm-manager
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    networks:
      Net1: 
        aliases:
          - spark-master

  spark-worker:
    image: medu5a/spark-master-worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf/worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost 
      constraint:role=: worker
    depends_on:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    networks: 
      Net1:

  hadoop-master:
    image: medu5a/hadoop-master-worker
    command: master
    hostname: hadoop-master
    ports:
      - 50070:50070
    environment:
      constraint:node=: swarm-manager
    networks:
      Net1:
        aliases:
          - hadoop-master

  hadoop-worker:
    image: medu5a/hadoop-master-worker
    command: worker
    hostname: hadoop-worker
    environment:
      constraint:role=: hadoop
    depends_on:
      - hadoop-master
    networks:
      Net1:

networks:
  Net1:
    driver: overlay
